# Generated by Django 2.2.7 on 2019-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnails',
            field=models.ImageField(null=True, upload_to='product-thumbnails'),
        ),
    ]
