# Generated by Django 2.2.7 on 2019-11-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_productimage_thumbnails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
