# Generated by Django 2.2.7 on 2019-11-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address1',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address2',
            field=models.CharField(blank=True, default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_zip_code',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
